swagger: "2.0"
info:
  description: "This the api documintation of the e-learning platform system."
  version: "1.0.0"
  title: "E-Learning Platform"
  contact:
    email: "iifawzie@gmail.com"
host: "localhost:5000"
basePath: "/api"
tags:
- name: "students"
  description: "Everything about students"
- name: "teachers"
  description: "Everything about teachers"
- name: "classes"
  description: "Everything about classes"
schemes:
- "http"
paths:
  /classes/:
    get:
      tags:
      - "classes"
      summary: "get all classes of teacher either he is the creator of group or helper."
      description: "This api is used to get all classes that teacher attached to"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: 200 (login Successfully)
          schema:
            $ref: '#/definitions/get_classes_response'
        '401':
          description: 401 (Not Authenticated - either the token is invalid, or refresh_token is incorrect)
          schema:
            $ref: '#/definitions/error_401'
        '403':
          description: 403 (Forbidden - Not Authorized)
          schema:
            $ref: '#/definitions/error_403'
  /teachers/refresh_token:
    post:
      tags:
      - "teachers"
      summary: "to get a new token for the teacher"
      description: "This api is used to get a new token"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "refresh_token that will be used to issue a new token"
        required: true
        schema:
          $ref: "#/definitions/teacher_refresh_token_body"
      - name: "authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: 200 (Success)
          schema:
            $ref: '#/definitions/teacher_refresh_token_response'
        '400':
          description: 400 (Bad Request - input is incorrect or missing)
          schema:
            $ref: '#/definitions/error_400'
        '401':
          description: 401 (Not Authenticated - either the token is invalid, or refresh_token is incorrect)
          schema:
            $ref: '#/definitions/error_401'
        '403':
          description: 403 (Forbidden - Not Authorized)
          schema:
            $ref: '#/definitions/error_403'
        '404':
          description: 404 (Account is not found)
          schema:
            $ref: '#/definitions/error_404'
  /teacher/signin:
    post:
      tags:
      - "teachers"
      summary: "signin a teacher"
      description: "This api is used to signin a tacher"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "teacher Info's object used to signin"
        required: true
        schema:
          $ref: "#/definitions/signin_teacher_body"
      responses:
        "200":
          description: 200 (login Successfully)
          schema:
            $ref: '#/definitions/signin_teacher_response'
        '400':
          description: 400 (Bad Request - input is incorrect or missing)
          schema:
            $ref: '#/definitions/error_400'
        '401':
          description: 401 (Not Authenticated - wrong phone_number or password)
          schema:
            $ref: '#/definitions/error_401'
  /classes/create:
    post:
      tags:
      - "classes"
      summary: "to create a new class"
      description: "This api is used to create a new class"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "the info need to create new class"
        required: true
        schema:
          $ref: "#/definitions/create_class_body"
      - name: "authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "201":
          description: 201 (Created)
          schema:
            $ref: '#/definitions/create_class_response'
        '400':
          description: 400 (Bad Request - input is incorrect or missing)
          schema:
            $ref: '#/definitions/error_400'
        '401':
          description: 401 (Not Authenticated - either the token is invalid, or refresh_token is incorrect)
          schema:
            $ref: '#/definitions/error_401'
        '403':
          description: 403 (Forbidden - Not Authorized)
          schema:
            $ref: '#/definitions/error_403'
  /teachers/create:
    post:
      tags:
      - "teachers"
      summary: "to create a new teacher"
      description: "This api is used to create a new teacher"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "the info need to create new teacher"
        required: true
        schema:
          $ref: "#/definitions/create_teacher_body"
      - name: "authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "201":
          description: 201 (Created)
          schema:
            $ref: '#/definitions/create_teacher_response'
        '400':
          description: 400 (Bad Request - input is incorrect or missing)
          schema:
            $ref: '#/definitions/error_400'
        '401':
          description: 401 (Not Authenticated - either the token is invalid, or refresh_token is incorrect)
          schema:
            $ref: '#/definitions/error_401'
        '403':
          description: 403 (Forbidden - Not Authorized)
          schema:
            $ref: '#/definitions/error_403'
        '409':
          description: 409 (CONFLICT - Resource already registered)
          schema:
            $ref: '#/definitions/error_409'
  /students/refresh_token:
    post:
      tags:
      - "students"
      summary: "to get a new token for the student"
      description: "This api is used to get a new token"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "refresh_token that will be used to issue a new token"
        required: true
        schema:
          $ref: "#/definitions/refresh_token_body"
      - name: "authorization"
        in: "header"
        required: true
        type: "string"
      responses:
        "200":
          description: 200 (Success)
          schema:
            $ref: '#/definitions/refresh_token_response'
        '400':
          description: 400 (Bad Request - input is incorrect or missing)
          schema:
            $ref: '#/definitions/error_400'
        '401':
          description: 401 (Not Authenticated - either the token is invalid, or refresh_token is incorrect)
          schema:
            $ref: '#/definitions/error_401'
        '403':
          description: 403 (Forbidden - Not Authorized)
          schema:
            $ref: '#/definitions/error_403'
        '404':
          description: 404 (Account is not found)
          schema:
            $ref: '#/definitions/error_404'
  /students/signup:
    post:
      tags:
      - "students"
      summary: "signup a new student"
      description: "This api is used to signup a student"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Student Info's object used to signup"
        required: true
        schema:
          $ref: "#/definitions/signup_student_body"
      responses:
        "201":
          description: 201 (Created Successfully)
          schema:
            $ref: '#/definitions/signup_student_response'
        '400':
          description: 400 (Bad Request - input is incorrect or missing)
          schema:
            $ref: '#/definitions/error_400'
        '409':
          description: 409 (CONFLICT - Resource already registered)
          schema:
            $ref: '#/definitions/error_409'
  /students/signin:
    post:
      tags:
      - "students"
      summary: "signin a student"
      description: "This api is used to signin a student"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Student Info's object used to signin"
        required: true
        schema:
          $ref: "#/definitions/signin_student_body"
      responses:
        "200":
          description: 200 (login Successfully)
          schema:
            $ref: '#/definitions/signin_student_response'
        '400':
          description: 400 (Bad Request - input is incorrect or missing)
          schema:
            $ref: '#/definitions/error_400'
        '401':
          description: 401 (Not Authenticated - wrong phone_number or password)
          schema:
            $ref: '#/definitions/error_401'
definitions:
  get_classes_response:
    type: "object"
    properties:
      class_id:
        type: "integer"
      class_name:
        type: "string"
      class_description:
        type: "string"
      class_code:
        type: "string"
      join_using:
        type: "string"
      creator_teacher_id:
        type: "integer"
    example:
      status: true
      message: success
      data:
        - class_id: 2
          class_name: Math 001
          class_description: 'The best class in the world, which is awesome really!'
          class_code: zocj4lei4
          join_using: code
          creator_teacher_id: 1
        - class_id: 4
          class_name: Arabic 2
          class_description: 'The best class in the world, which is awesome really!'
          class_code: i2u8yni5n
          join_using: code
          creator_teacher_id: 2
  teacher_refresh_token_body:
    type: "object"
    properties:
      teacher_refresh_token:
        type: "string"
    example:
      teacher_refresh_token: "7a92299daf865ace374e999c2fe02234"
  teacher_refresh_token_response:
    type: "object"
    properties:
      token:
        type: "string"
    example:
      authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjoxLCJzdHVkZW50X25hbWUiOiJGYXd6aSIsInBob25lX251bWJlciI6IjAxMDkwMjQzNzk1Iiwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE2MDMwNTgwODksImV4cCI6MTYwMzE0NDQ4OX0.rzuImCu26vMTEu82DKlHdqGYyWwHnj2O4_J6oSz6kS0"
  signin_teacher_body:
    type: "object"
    properties:
      teacher_phone_number:
        type: "string"
      password:
        type: "string"
    example:
      phone_number: "01090243795"
      password: "12qwaszx"
  signin_teacher_response:
    type: "object"
    properties:
      teacher_name:
        type: "string"
      tacher_phone_number:
        type: "string"
      teacher_id:
        type: "integer"
      teacher_refresh_token:
        type: "string"
      token:
        type: "string"
    example: 
      status: true
      message: success
      data:
        teacher_id: 1
        teacher_phone_number: 01090243795
        teacher_name: Fawzi E. Abdulfattah
        teacher_refresh_token: 7c3a91193adb19db3bf0da4da2b79d15
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVyX2lkIjoxLCJ0ZWFjaGVyX25hbWUiOiJGYXd6aSBFLiBBYmR1bGZhdHRhaCIsInBob25lX251bWJlciI6IjAxMDkwMjQzNzk1Iiwicm9sZSI6InRlYWNoZXIiLCJpYXQiOjE2MDQ1NjY3MTUsImV4cCI6MTYwNDY1MzExNX0.fjsEMgmrSaXiNaTrPTowXiFHvMu3fR2KheCFtavS0mA
  create_class_body:
    type: "object"
    properties:
      class_name:
        type: "string"
      class_description:
        type: "string"
      join_using:
        type: "string"
    example:
      class_name: Math 001
      class_description: 'Math''s class, the best one ever.'
      join_using: code
  create_class_response:
    type: "object"
    properties:
      class_id:
        type: "integer"
      class_name:
        type: "string"
      class_description:
        type: "string"
      join_using:
        type: "string"
      teacher_id:
        type: "integer"
    example:
      status: true
      message: success
      data:
        class_id: 4
        class_name: Math 001
        class_description: 'Math''s class, the best one ever.'
        join_using: code
        teacher_id: 1
        class_code: uhizknok8
        updatedAt: '2020-11-02T02:50:14.350Z'
        createdAt: '2020-11-02T02:50:14.350Z'
  create_teacher_body:
    type: "object"
    properties:
      teacher_name:
        type: "string"
      teacher_phone_number:
        type: "string"
      password:
        type: "string"
      teacher_role:
        type: "string"
    example:
      teacher_name: Fawzi E. Abdulfattah
      teacher_phone_number: 01090243795
      teacher_pasword: 12qwaszx
      teacher_role: principle
  create_teacher_response:
    type: "object"
    properties:
      teacher_name:
        type: "string"
      teacher_phone_number:
        type: "string"
      password:
        type: "string"
      teacher_role:
        type: "string"
      refresh_token:
        type: "string"
      token:
        type: "string"
    example:
      status: true
      message: success
      data:
        teacher_id: 1
        teacher_name: Fawzi E. Abdulfattah
        teacher_phone_number: 01090243795
        teacher_role: principle
        teacher_refresh_token: 65ba2902eaa8df8594b5c532dc0eacb3
        updatedAt: '2020-11-02T00:11:02.821Z'
        createdAt: '2020-11-02T00:11:02.821Z'
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0ZWFjaGVyX2lkIjoxLCJ0ZWFjaGVyX25hbWUiOiJGYXd6aSBFLiBBYmR1bGZhdHRhaCIsInBob25lX251bWJlciI6IjAxMDkwMjQzNzk1Iiwicm9sZSI6InByaW5jaXBsZSIsImlhdCI6MTYwNDI3NTg2MiwiZXhwIjoxNjA0MzYyMjYyfQ.3rbYYS6_HKoEcogNkAct48eLph0N1ACOms4gRS4AQC0
  refresh_token_body:
    type: "object"
    properties:
      refresh_token:
        type: "string"
    example:
      refresh_token: "7a92299daf865ace374e999c2fe02234"
  refresh_token_response:
    type: "object"
    properties:
      token:
        type: "string"
    example:
      authorization: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjoxLCJzdHVkZW50X25hbWUiOiJGYXd6aSIsInBob25lX251bWJlciI6IjAxMDkwMjQzNzk1Iiwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE2MDMwNTgwODksImV4cCI6MTYwMzE0NDQ4OX0.rzuImCu26vMTEu82DKlHdqGYyWwHnj2O4_J6oSz6kS0"
  signin_student_body:
    type: "object"
    properties:
      phone_number:
        type: "string"
      password:
        type: "string"
    example:
      phone_number: "01090243795"
      password: "12qwaszx"
  signin_student_response:
    type: "object"
    properties:
      student_name:
        type: "string"
      phone_number:
        type: "string"
      student_id:
        type: "integer"
      refresh_token:
        type: "string"
      token:
        type: "string"
    example: 
      status: true
      message: success
      data:
        student_id: 1
        phone_number: 01090243795
        student_name: Fawzi
        refresh_token: 7a92299daf865ace374e999c2fe02234
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjoxLCJzdHVkZW50X25hbWUiOiJGYXd6aSIsInBob25lX251bWJlciI6IjAxMDkwMjQzNzk1Iiwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE2MDMwNTgwODksImV4cCI6MTYwMzE0NDQ4OX0.rzuImCu26vMTEu82DKlHdqGYyWwHnj2O4_J6oSz6kS0
  signup_student_body:
    type: "object"
    properties:
      student_name:
        type: "string"
      phone_number:
        type: "string"
      password:
        type: "string"
  signup_student_response:
    type: "object"
    properties:
      student_name:
        type: "string"
      phone_number:
        type: "string"
      student_id:
        type: "integer"
      subscription_end_date:
        type: "string"
      account_status:
        type: boolean
      refresh_token:
        type: "string"
      token:
        type: "string"
    example: 
      status: true
      message: success
      data:
        account_status: false
        student_id: 4
        student_name: Fawzi
        phone_number: 01090243795
        refresh_token: 69ffe2a19d204371bceb28170b545052
        subscription_end_date: '2020-11-18'
        updatedAt: '2020-10-18T01:13:00.283Z'
        createdAt: '2020-10-18T01:13:00.283Z'
        token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdHVkZW50X2lkIjo0LCJzdHVkZW50X25hbWUiOiJGYXd6aSIsInBob25lX251bWJlciI6IjAxMDkwMjQzNzk1Iiwicm9sZSI6InN0dWRlbnQiLCJpYXQiOjE2MDI5ODM1ODAsImV4cCI6MTYwMzA2OTk4MH0.u5hPv2oOq39G_1CAS_bOBG4lAYrT2yQobooAYSCGprQ
  error_409:
    type: "object"
    description: "CONFLICT"
    example:
      status: false
      message: "Error explaniation will be shown here"
      data: []
  error_401:
    type: "string"
    description: "Unauthorized"
    example:
      status: false
      message: "Error explaniation will be shown here"
      data: []
  error_400:
    type: "string"
    description: "Bad Request"
    example:
      status: false
      message: "Error explaniation will be shown here"
      data: []
  error_403:
    type: "string"
    description: "Forbidden"
    example:
      status: false
      message: "Error explaniation will be shown here"
      data: []
  error_404:
    type: "string"
    description: "Not Found"
    example:
      status: false
      message: "Error explaniation will be shown here"
      data: []